const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='busterbuildProCRM';
const READ_KEY='busterbuildCRMNotificationReads';
let notificationReads=JSON.parse(localStorage.getItem(READ_KEY)||'[]');
const base={customers:[{name:'Thabo Mokoena',phone:'071 123 4567',type:'Contractor',purchase:'12 Aug 2026',spend:8450,owner:'Moses M.'},{name:'Moses Moyana',phone:'061 443 8789',type:'Business',purchase:'11 Aug 2026',spend:12700,owner:'Linda P.'},{name:'John Builders',phone:'073 345 6789',type:'Developer',purchase:'11 Aug 2026',spend:24300,owner:'Moses M.'},{name:'Pumza Construction',phone:'074 456 7890',type:'Contractor',purchase:'10 Aug 2026',spend:18900,owner:'Linda P.'},{name:'Dlamini Projects',phone:'075 567 8901',type:'Business',purchase:'9 Aug 2026',spend:31250,owner:'Jabulani T.'}],leads:[['Nkosi Renovations','New','Paint & accessories','R18,500'],['Bright Build','New','Building materials','R9,800'],['Maphosa Contractors','Contacted','Cement & tools','R32,400'],['HomeFix SA','Contacted','Plumbing','R14,200'],['Urban Projects','Quote Sent','Tiles & sanitary ware','R48,700'],['Thando Build','Quote Sent','Electrical','R21,300'],['Khosa Developments','Won','Building materials','R62,900']],tasks:[],followups:[{customer:'Thabo Mokoena',purpose:'Quote follow-up',owner:'Moses M.',due:'2026-08-19',priority:'High',status:'Open'},{customer:'Moses Moyana',purpose:'Invoice reminder',owner:'Linda P.',due:'2026-08-20',priority:'Medium',status:'Open'},{customer:'John Builders',purpose:'Product enquiry',owner:'Moses M.',due:'2026-08-21',priority:'High',status:'Open'},{customer:'Pumza Construction',purpose:'Order confirmation',owner:'Linda P.',due:'2026-08-22',priority:'Medium',status:'Open'},{customer:'Dlamini Projects',purpose:'Payment follow-up',owner:'Jabulani T.',due:'2026-08-23',priority:'Low',status:'Open'}],quotes:[['QT-2081','Thabo Mokoena','R8,450','18 Aug 2026','25 Aug 2026','Sent'],['QT-2080','Urban Projects','R48,700','17 Aug 2026','24 Aug 2026','Viewed'],['QT-2079','Khosa Developments','R62,900','16 Aug 2026','23 Aug 2026','Accepted']],invoices:[['INV-1256','John Builders','R24,300','20 Aug 2026','Paid'],['INV-1255','Pumza Construction','R18,900','19 Aug 2026','Sent'],['INV-1254','Dlamini Projects','R31,250','15 Aug 2026','Overdue']],sales:[['ORD-8841','John Builders','Linda P.','R24,300','18 Aug 2026','Completed'],['ORD-8840','Thabo Mokoena','Moses M.','R8,450','18 Aug 2026','Completed'],['ORD-8839','Pumza Construction','Linda P.','R18,900','17 Aug 2026','Processing']],products:[['Cement 42.5N 50kg','Building Materials','R98.00','In stock','320'],['RhinoLite 20kg','Building Materials','R145.00','In stock','84'],['Angle Grinder 115mm','Tools & Equipment','R899.00','Low stock','12'],['PVC Pipe 110mm','Plumbing','R129.00','In stock','76'],['Acrylic PVA 20L','Paint','R1,499.00','In stock','34']],employees:[['Moses M.','Sales Representative','R248,600','83%'],['Linda P.','Sales Representative','R198,300','79%'],['Jabulani T.','Sales Representative','R156,700','78%'],['Sipho D.','Sales Representative','R98,400','66%'],['Zanele M.','Sales Representative','R68,900','57%']]};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||base;
if(!data.tasks)data.tasks=[];
if(!data.employees)data.employees=[];
// Keep older saved employee records compatible while allowing rich employee profiles.
data.employees=data.employees.map(e=>Array.isArray(e)?{name:e[0],role:e[1],target:e[2],achievement:e[3],phone:'',email:''}:e);
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=n=>'R'+Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:0,maximumFractionDigits:0});
function toast(msg){const t=$('#toast');$('.toast span').textContent=msg;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2600)}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('open');setTimeout(()=>$('#modal input, #modal select, #modal textarea')?.focus(),60)}
function closeModal(){$('#modal').classList.remove('open')}
$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
function navigate(view){$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+view));$$('#nav a').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});render(view)}
$('#nav').onclick=e=>{const a=e.target.closest('a[data-view]');if(a){e.preventDefault();navigate(a.dataset.view)}};
document.addEventListener('click',e=>{const v=e.target.closest('[data-view-target]');if(v)navigate(v.dataset.viewTarget);const a=e.target.closest('[data-action]');if(a)action(a.dataset.action)});
$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');
$('#supportBtn').onclick=()=>window.open('https://wa.me/27632513656','_blank');
$('#profileBtn').onclick=()=>toast('Administrator profile is active');
$('#notificationBtn').onclick=(e)=>{e.stopPropagation();toggleNotifications()};
$('#markNotificationsRead').onclick=(e)=>{e.stopPropagation();markNotificationsRead()};
$('#workspaceBtn').onclick=()=>toast('BusterBuild Hardware workspace selected');
document.addEventListener('click',e=>{if(!e.target.closest('.notification-wrap'))closeNotifications()});$('#dateBtn').onclick=()=>toast('Today is '+new Date().toLocaleDateString('en-ZA',{day:'numeric',month:'long',year:'numeric'}));
$('#globalSearch').oninput=e=>{const q=e.target.value.toLowerCase().trim();if(!q)return;const hit=data.customers.find(c=>(c.name+' '+c.phone).toLowerCase().includes(q))||data.tasks.find(t=>(t.title+' '+t.assignee).toLowerCase().includes(q));if(hit){navigate(data.tasks.includes(hit)?'tasks':'customers');toast('Search result found')}else toast('No matching CRM record found')};
function action(type){if(type==='customer')return customerForm();if(type==='task')return taskForm();if(type==='lead')return leadForm();if(type==='followup')return followupForm();if(type==='quote')return simpleForm('quote');if(type==='invoice')return simpleForm('invoice');if(type==='sale')return simpleForm('sale');if(type==='product')return simpleForm('product');if(type==='employee')return simpleForm('employee');if(type==='message')return simpleForm('message');if(type==='export')return exportReport()}
function customerForm(){openModal(`<span class="eyebrow">CUSTOMER MANAGEMENT</span><h2>Add customer</h2><p>Create a complete customer profile for your team.</p><form id="customerForm" class="form"><div class="two"><label>Full name<input name="name" required placeholder="e.g. Thabo Mokoena"></label><label>Phone<input name="phone" required placeholder="071 123 4567"></label><label>Email<input name="email" type="email" placeholder="customer@email.com"></label><label>Type<select name="type"><option>Retail</option><option>Contractor</option><option>Business</option><option>Developer</option></select></label></div><label>Notes<textarea name="notes" placeholder="Requirements or customer notes"></textarea></label><button class="btn primary full">Save Customer</button></form>`);$('#customerForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.customers.unshift({name:f.get('name'),phone:f.get('phone'),type:f.get('type'),purchase:'New',spend:0,owner:'Unassigned'});save();closeModal();renderAll();navigate('customers');toast('Customer added successfully')}}
function taskForm(){const people=data.employees.length?data.employees.map(e=>`<option>${esc(e.name)}</option>`).join(''):'<option value="Unassigned">Unassigned — add employees first</option>';openModal(`<span class="eyebrow">TEAM OPERATIONS</span><h2>Create staff task</h2><p>Assign a clear responsibility with a deadline.</p><form id="taskForm" class="form"><label>Task title<input name="title" required placeholder="e.g. Call John Builders about quote"></label><div class="two"><label>Assign to<select name="assignee">${people}</select></label><label>Priority<select name="priority"><option>High</option><option>Medium</option><option>Low</option></select></label><label>Due date<input name="due" type="date" required value="2026-08-20"></label><label>Category<select name="category"><option>Sales</option><option>Customer Care</option><option>Stock</option><option>Finance</option><option>Administration</option></select></label></div><label>Details<textarea name="details" placeholder="Add instructions..."></textarea></label><button class="btn primary full">Create Task</button></form>`);$('#taskForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.tasks.unshift({id:Date.now(),title:f.get('title'),assignee:f.get('assignee'),priority:f.get('priority'),due:f.get('due'),category:f.get('category'),details:f.get('details'),status:'Open'});save();closeModal();renderAll();navigate('tasks');toast('Task assigned to '+f.get('assignee'))}}
function leadForm(){openModal(`<span class="eyebrow">PIPELINE</span><h2>Add lead</h2><form id="leadForm" class="form"><div class="two"><label>Company / customer<input name="name" required></label><label>Stage<select name="stage"><option>New</option><option>Contacted</option><option>Quote Sent</option><option>Won</option></select></label><label>Interest<input name="interest" placeholder="Cement, tiles, tools..."></label><label>Potential value<input name="value" placeholder="R25,000"></label></div><button class="btn primary full">Add Lead</button></form>`);$('#leadForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.leads.push([f.get('name'),f.get('stage'),f.get('interest'),f.get('value')||'R0']);save();closeModal();renderAll();navigate('leads');toast('Lead added to pipeline')}}
function followupForm(){openModal(`<span class="eyebrow">CUSTOMER CARE</span><h2>Schedule follow-up</h2><form id="followForm" class="form"><div class="two"><label>Customer<input name="customer" required></label><label>Purpose<input name="purpose" required placeholder="Quote follow-up"></label><label>Assigned to<select name="owner"><option>Moses M.</option><option>Linda P.</option><option>Jabulani T.</option><option>Patel Idreas</option></select></label><label>Due date<input name="due" type="date" required value="2026-08-20"></label><label>Priority<select name="priority"><option>High</option><option>Medium</option><option>Low</option></select></label></div><button class="btn primary full">Schedule Follow-up</button></form>`);$('#followForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.followups.unshift({customer:f.get('customer'),purpose:f.get('purpose'),owner:f.get('owner'),due:f.get('due'),priority:f.get('priority'),status:'Open'});save();closeModal();renderAll();navigate('followups');toast('Follow-up scheduled')}}
function employeeForm(index=null){
 const editing=index!==null&&data.employees[index];
 const e=editing?data.employees[index]:{name:'',role:'Sales Representative',phone:'',email:'',target:''};
 const val=x=>esc(x||'');
 openModal(`<span class="eyebrow">TEAM SETUP</span><h2>${editing?'Edit employee':'Add employee'}</h2><p>${editing?'Update this team member\'s details. Changes will flow through task assignment immediately.':'Enter the staff member\'s real details. Their name will instantly become available when you assign tasks.'}</p><form id="employeeForm" class="form"><div class="two"><label>Full name<input name="name" required value="${val(e.name)}" placeholder="e.g. Thabo Mokoena"></label><label>Role<select name="role"><option ${e.role==='Sales Representative'?'selected':''}>Sales Representative</option><option ${e.role==='Store Assistant'?'selected':''}>Store Assistant</option><option ${e.role==='Cashier'?'selected':''}>Cashier</option><option ${e.role==='Stock Controller'?'selected':''}>Stock Controller</option><option ${e.role==='Driver / Delivery'?'selected':''}>Driver / Delivery</option><option ${e.role==='Manager'?'selected':''}>Manager</option><option ${e.role==='Administrator'?'selected':''}>Administrator</option></select></label><label>Phone number<input name="phone" value="${val(e.phone)}" placeholder="e.g. 071 123 4567"></label><label>Email address<input name="email" type="email" value="${val(e.email)}" placeholder="employee@busterbuild.co.za"></label><label>Monthly target<input name="target" value="${val(e.target)}" placeholder="e.g. R250,000"></label></div><button class="btn primary full"><i class="fa-solid fa-user-check"></i>${editing?'Save changes':'Save employee'}</button></form>`);
 $('#employeeForm').onsubmit=ev=>{ev.preventDefault();const f=new FormData(ev.target);const person={name:String(f.get('name')).trim(),role:f.get('role'),phone:String(f.get('phone')).trim(),email:String(f.get('email')).trim(),target:String(f.get('target')).trim()||'Not set'};if(editing){const oldName=data.employees[index].name;data.employees[index]=person;data.tasks.forEach(t=>{if(t.assignee===oldName)t.assignee=person.name});data.followups.forEach(fu=>{if(fu.owner===oldName)fu.owner=person.name});toast(person.name+' details updated')}else{data.employees.unshift(person);toast(person.name+' added to the team')}save();closeModal();renderAll();navigate('employees')};
}

function simpleForm(type){const titles={quote:'Create quote',invoice:'Create invoice',sale:'Record sale',product:'Add product',employee:'Add employee',message:'New message'};openModal(`<span class="eyebrow">CRM WORKSPACE</span><h2>${titles[type]}</h2><form id="simpleForm" class="form"><div class="two"><label>Name / customer<input name="name" required placeholder="Enter name"></label><label>Reference / amount<input name="value" placeholder="R0.00"></label></div><label>Notes<textarea name="notes" placeholder="Add details..."></textarea></label><button class="btn primary full">Save ${titles[type]}</button></form>`);$('#simpleForm').onsubmit=e=>{e.preventDefault();closeModal();toast(titles[type]+' saved successfully');renderAll()}}
function render(view){if(view==='customers')renderCustomers();if(view==='leads')renderLeads();if(view==='sales')renderSales();if(view==='quotes')renderQuotes();if(view==='invoices')renderInvoices();if(view==='products')renderProducts();if(view==='communication')renderInbox();if(view==='followups')renderFollowups();if(view==='tasks')renderTasks();if(view==='employees')renderEmployees();if(view==='dashboard')renderDashboard()}
function renderDashboard(){const open=data.tasks.filter(t=>t.status!=='Completed');$('#dashboardTasks').innerHTML=open.length?open.slice(0,4).map(taskHTML).join(''):`<div class="empty"><i class="fa-solid fa-circle-check"></i><b>No staff tasks yet</b><small>Create tasks and assign them to your team.</small></div>`;$('#dashboardFollowups').innerHTML=data.followups.slice(0,4).map(f=>`<div class="mini-follow"><span class="avatar-sm">${esc(f.customer.split(' ').map(x=>x[0]).slice(0,2).join(''))}</span><p><b>${esc(f.customer)}</b><small>${esc(f.purpose)}</small></p><time>${esc(formatDate(f.due))}</time></div>`).join('');}
function renderCustomers(){const q=($('[data-table-search="customers"]')?.value||'').toLowerCase();$('#customersBody').innerHTML=data.customers.filter(c=>(c.name+' '+c.phone+' '+c.type).toLowerCase().includes(q)).map((c,i)=>`<tr><td><div class="person"><span class="avatar-sm">${esc(c.name.split(' ').map(x=>x[0]).slice(0,2).join(''))}</span><b>${esc(c.name)}</b></div></td><td>${esc(c.phone)}</td><td>${esc(c.type)}</td><td>${esc(c.purchase)}</td><td class="amount">${money(c.spend)}</td><td>${esc(c.owner)}</td><td><span class="badge success">Active</span></td><td><button class="dots" onclick="toast('Customer options ready')">•••</button></td></tr>`).join('')}
function renderLeads(){const stages=['New','Contacted','Quote Sent','Won'];$('#pipeline').innerHTML=stages.map(s=>{const items=data.leads.filter(l=>l[1]===s);return `<div class="stage"><header><b>${s}</b><span>${items.length}</span></header>${items.map(l=>`<article><b>${esc(l[0])}</b><small>${esc(l[2])}</small><strong>${esc(l[3])}</strong><button onclick="toast('Lead moved to ${s}')">Open lead <i class="fa-solid fa-arrow-right"></i></button></article>`).join('')||'<div class="empty">No leads here</div>'}</div>`}).join('')}
function renderSales(){$('#salesBody').innerHTML=data.sales.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td class="amount">${r[3]}</td><td>${r[4]}</td><td><span class="badge success">${r[5]}</span></td></tr>`).join('')}
function renderQuotes(){$('#quotesBody').innerHTML=data.quotes.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td class="amount">${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td><span class="badge ${r[5]==='Accepted'?'success':'info'}">${r[5]}</span></td><td><button class="dots" onclick="toast('Quote ${r[0]} opened')">•••</button></td></tr>`).join('')}
function renderInvoices(){$('#invoicesBody').innerHTML=data.invoices.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td class="amount">${r[2]}</td><td>${r[3]}</td><td><span class="badge ${r[4]==='Paid'?'success':r[4]==='Overdue'?'danger':'warning'}">${r[4]}</span></td><td><button class="dots" onclick="toast('Invoice ${r[0]} opened')">•••</button></td></tr>`).join('')}
function renderProducts(){$('#productGrid').innerHTML=data.products.map(p=>`<div class="product"><div class="product-icon"><i class="fa-solid fa-box"></i></div><div><b>${p[0]}</b><small>${p[1]}</small></div><strong>${p[2]}</strong><span class="stock ${p[3]==='Low stock'?'low':''}">${p[3]} • ${p[4]}</span><button onclick="toast('${esc(p[0])} selected')">Manage <i class="fa-solid fa-arrow-right"></i></button></div>`).join('')}
function renderInbox(){$('#inbox').innerHTML=['Thabo Mokoena','John Builders','Pumza Construction','Dlamini Projects'].map((x,i)=>`<button class="inbox-item ${i===0?'selected':''}" onclick="selectConversation('${x}')"><span class="avatar-sm">${x.split(' ').map(a=>a[0]).join('').slice(0,2)}</span><span><b>${x}</b><small>${['Can you send the quote?','Payment has been made.','Please confirm delivery.','Need pricing on cement.'][i]}</small></span><time>${i+1}h</time></button>`).join('');selectConversation('Thabo Mokoena')}
window.selectConversation=name=>{$('#conversationBody').innerHTML=`<div class="message them"><b>${esc(name)}</b><p>Hello, I need an update on my BusterBuild order.</p><time>18:32</time></div><div class="message me"><p>Hi ${esc(name)}, absolutely. I am checking this for you now.</p><time>18:34</time></div>`};
$('#messageForm').onsubmit=e=>{e.preventDefault();const v=$('#messageInput').value.trim();if(v){$('#conversationBody').insertAdjacentHTML('beforeend',`<div class="message me"><p>${esc(v)}</p><time>Now</time></div>`);$('#messageInput').value='';toast('Message sent')}};
function renderFollowups(){$('#followupsBody').innerHTML=data.followups.map((f,i)=>`<tr><td><b>${esc(f.customer)}</b></td><td>${esc(f.purpose)}</td><td>${esc(f.owner)}</td><td>${formatDate(f.due)}</td><td><span class="badge ${f.priority==='High'?'danger':f.priority==='Medium'?'warning':'neutral'}">${f.priority}</span></td><td><button class="status-btn ${f.status==='Completed'?'done':''}" onclick="toggleFollow(${i})">${f.status==='Completed'?'Completed':'Mark done'}</button></td><td><button class="dots" onclick="toast('Follow-up options ready')">•••</button></td></tr>`).join('')}
window.toggleFollow=i=>{data.followups[i].status=data.followups[i].status==='Completed'?'Open':'Completed';save();renderAll();toast('Follow-up updated')};
function taskHTML(t){return `<div class="task"><button class="check ${t.status==='Completed'?'checked':''}" onclick="toggleTask(${t.id})"><i class="fa-solid fa-check"></i></button><div><b>${esc(t.title)}</b><small>${esc(t.assignee)} • ${formatDate(t.due)} • ${esc(t.category)}</small></div><span class="badge ${t.priority==='High'?'danger':t.priority==='Medium'?'warning':'neutral'}">${t.priority}</span></div>`}
window.toggleTask=id=>{const t=data.tasks.find(x=>x.id===id);if(t){t.status=t.status==='Completed'?'Open':'Completed';save();renderAll();toast(t.status==='Completed'?'Task marked complete':'Task reopened')}};
function renderTasks(){const now=new Date();const open=data.tasks.filter(t=>t.status==='Open').length,progress=data.tasks.filter(t=>t.status==='In Progress').length,done=data.tasks.filter(t=>t.status==='Completed').length,over=data.tasks.filter(t=>t.status!=='Completed'&&new Date(t.due)<now).length;$('#taskOpen').textContent=open;$('#taskProgress').textContent=progress;$('#taskCompleted').textContent=done;$('#taskOverdue').textContent=over;$('#taskBoard').innerHTML=data.tasks.length?data.tasks.map(t=>`<div class="task-row">${taskHTML(t)}<div class="task-actions"><button onclick="setTaskProgress(${t.id})">${t.status==='In Progress'?'In progress':'Start'}</button><button onclick="deleteTask(${t.id})"><i class="fa-solid fa-trash"></i></button></div></div>`).join(''):`<div class="empty large"><i class="fa-solid fa-list-check"></i><b>No tasks created yet</b><small>Create a task to start managing your staff workflow.</small><button class="btn primary" data-action="task">Create First Task</button></div>`}
window.setTaskProgress=id=>{const t=data.tasks.find(x=>x.id===id);if(t){t.status=t.status==='In Progress'?'Open':'In Progress';save();renderAll();toast('Task status updated')}};window.deleteTask=id=>{data.tasks=data.tasks.filter(x=>x.id!==id);save();renderAll();toast('Task deleted')};
function employeeInitials(name){return String(name||'Team').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function renderEmployees(){
 const open=data.tasks.filter(t=>t.status!=='Completed').length,done=data.tasks.filter(t=>t.status==='Completed').length,over=data.tasks.filter(t=>t.status!=='Completed'&&new Date(t.due)<new Date()).length;
 $('#teamMemberCount').textContent=data.employees.length;$('#teamOpenTasks').textContent=open;$('#teamCompletedTasks').textContent=done;$('#teamOverdueTasks').textContent=over;
 $('#teamHeadline').textContent=data.employees.length?`${data.employees.length} team member${data.employees.length===1?'':'s'} connected`:'Build your store team';
 $('#teamSubline').textContent=data.employees.length?'Employees can now receive tasks, deadlines and performance tracking from one place.':'Add each employee once. Their names will automatically appear in task assignment and team performance.';
 $('#employeeGrid').innerHTML=data.employees.length?data.employees.map((e,i)=>{const assigned=data.tasks.filter(t=>t.assignee===e.name&&t.status!=='Completed').length,completed=data.tasks.filter(t=>t.assignee===e.name&&t.status==='Completed').length,percent=completed+assigned?Math.round(completed/(completed+assigned)*100):0;return `<div class="employee employee-pro"><span class="avatar-lg">${employeeInitials(e.name)}</span><div><div class="employee-top"><div><h3>${esc(e.name)}</h3><p>${esc(e.role||'Staff member')}</p></div><span class="employee-status"><i></i> Active</span></div><small>${e.phone?esc(e.phone):'No phone added'} ${e.email?'• '+esc(e.email):''}</small><div class="employee-workload"><span>Task completion</span><b>${percent}%</b></div><div class="progress"><i style="width:${percent}%"></i></div><div class="employee-stats"><span><b>${assigned}</b> open</span><span><b>${completed}</b> completed</span><span><b>${esc(e.target||'No target')}</b> target</span></div></div><button onclick="openEmployeeActions(${i})">Manage <i class="fa-solid fa-arrow-right"></i></button></div>`}).join(''):`<div class="empty large team-empty"><div class="empty-team-icon"><i class="fa-solid fa-user-plus"></i></div><b>No employees added yet</b><small>Tomorrow, enter your actual store employees here. Once added, their names appear in the task assignment menu automatically.</small><button class="btn primary" data-action="employee"><i class="fa-solid fa-user-plus"></i>Add first employee</button></div>`;
}
function formatDate(v){if(!v)return '-';const d=new Date(v+'T00:00:00');return d.toLocaleDateString('en-ZA',{day:'2-digit',month:'short',year:'numeric'})}
function exportReport(){const rows=[['BusterBuild CRM Export',''],['Customers',data.customers.length],['Open tasks',data.tasks.filter(t=>t.status!=='Completed').length],['Completed tasks',data.tasks.filter(t=>t.status==='Completed').length],['Follow-ups',data.followups.length]];const blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='busterbuild-crm-report.csv';a.click();URL.revokeObjectURL(url);toast('CRM report exported')}
function getNotifications(){const out=[];const now=new Date();data.tasks.filter(t=>t.status!=='Completed').forEach(t=>{const due=new Date(t.due+'T23:59:59');const overdue=due<now;out.push({id:'task-'+t.id,type:overdue?'danger':'task',icon:overdue?'fa-triangle-exclamation':'fa-list-check',title:overdue?'Task overdue':'Task assigned',text:`${t.title} • ${t.assignee}`,meta:overdue?'Overdue':'Due '+formatDate(t.due),view:'tasks'})});data.followups.filter(f=>f.status!=='Completed').forEach((f,i)=>{const due=new Date(f.due+'T23:59:59');const overdue=due<now;out.push({id:'follow-'+i,type:overdue?'danger':'follow',icon:'fa-calendar-check',title:overdue?'Follow-up overdue':'Follow-up reminder',text:`${f.customer} • ${f.purpose}`,meta:formatDate(f.due),view:'followups'})});data.invoices.filter(r=>r[4]==='Overdue').forEach(r=>out.push({id:'invoice-'+r[0],type:'danger',icon:'fa-file-invoice-dollar',title:'Invoice overdue',text:`${r[0]} • ${r[1]} • ${r[2]}`,meta:'Needs attention',view:'invoices'}));return out.sort((a,b)=>(b.type==='danger')-(a.type==='danger')).slice(0,12)}
function renderNotifications(){const all=getNotifications(),unread=all.filter(n=>!notificationReads.includes(n.id));$('#notificationCount').textContent=unread.length;$('#notificationCount').style.display=unread.length?'grid':'none';$('#notificationSummary').textContent=unread.length?`${unread.length} item${unread.length===1?'':'s'} need your attention`:'You are all caught up.';$('#notificationList').innerHTML=all.length?all.map(n=>`<button class="notification-item ${notificationReads.includes(n.id)?'read':''}" data-notification-id="${n.id}" data-notification-view="${n.view}"><span class="notification-icon ${n.type}"><i class="fa-solid ${n.icon}"></i></span><span><b>${esc(n.title)}</b><small>${esc(n.text)}</small><time>${esc(n.meta)}</time></span><i class="fa-solid fa-chevron-right"></i></button>`).join(''):`<div class="notification-empty"><i class="fa-solid fa-circle-check"></i><b>No new notifications</b><small>Your CRM is clear.</small></div>`}
function toggleNotifications(){const p=$('#notificationPanel'),open=p.classList.toggle('open');p.setAttribute('aria-hidden',String(!open));$('#notificationBtn').setAttribute('aria-expanded',String(open));if(open)renderNotifications()}
function closeNotifications(){const p=$('#notificationPanel');if(p.classList.contains('open')){p.classList.remove('open');p.setAttribute('aria-hidden','true');$('#notificationBtn').setAttribute('aria-expanded','false')}}
function markNotificationsRead(){notificationReads=[...new Set([...notificationReads,...getNotifications().map(n=>n.id)])];localStorage.setItem(READ_KEY,JSON.stringify(notificationReads));renderNotifications();toast('All notifications marked as read')}
document.addEventListener('click',e=>{const n=e.target.closest('[data-notification-id]');if(n){const id=n.dataset.notificationId;if(!notificationReads.includes(id)){notificationReads.push(id);localStorage.setItem(READ_KEY,JSON.stringify(notificationReads))}closeNotifications();navigate(n.dataset.notificationView)}});
function openEmployeeActions(index){const e=data.employees[index];const open=data.tasks.filter(t=>t.assignee===e.name&&t.status!=='Completed').length;openModal(`<span class="eyebrow">TEAM MEMBER</span><h2>${esc(e.name)}</h2><p>${esc(e.role||'Staff member')} • ${open} open task${open===1?'':'s'}</p><div class="employee-action-grid"><button class="btn primary" onclick="closeModal();employeeForm(${index})"><i class="fa-solid fa-user-pen"></i>Edit details</button><button class="btn ghost" onclick="closeModal();taskFormFor('${esc(e.name).replace(/'/g,'&#039;')}')"><i class="fa-solid fa-list-check"></i>Assign task</button><button class="btn ghost" onclick="closeModal();navigate('tasks')"><i class="fa-solid fa-chart-line"></i>View tasks</button><button class="btn ghost danger-action" onclick="removeEmployee(${index})"><i class="fa-solid fa-user-minus"></i>Remove employee</button></div>`)}
window.taskFormFor=name=>{taskForm();setTimeout(()=>{const s=$('#taskForm select[name=assignee]');if(s){s.value=name}},70)};window.removeEmployee=index=>{const e=data.employees[index];if(!confirm('Remove '+e.name+' from the team? Existing tasks will remain.'))return;data.employees.splice(index,1);save();closeModal();renderAll();toast(e.name+' removed from team')};
function renderAll(){save();renderNotifications();$('#navCustomers').textContent=data.customers.length;$('#navLeads').textContent=data.leads.length;$('#navFollowups').textContent=data.followups.filter(f=>f.status!=='Completed').length;$('#navTasks').textContent=data.tasks.filter(t=>t.status!=='Completed').length;$('#statCustomers').textContent=data.customers.length;$('#statLeads').textContent=data.leads.filter(l=>l[1]!=='Won').length;$('#statTasks').textContent=data.tasks.filter(t=>t.status!=='Completed').length;$('#statTasksText').textContent=data.tasks.length?`${data.tasks.filter(t=>t.status==='Completed').length} completed`:'Create your first task';renderDashboard();const active=$('.view.active')?.id?.replace('view-','');if(active&&active!=='dashboard')render(active)}
$$('[data-table-search]').forEach(i=>i.oninput=()=>renderCustomers());$('#saveSettings').onclick=()=>{save();toast('Settings saved successfully')};$('#todayDate').textContent=new Date().toLocaleDateString('en-ZA',{day:'numeric',month:'long',year:'numeric'});renderAll();
